server:
  port: 8888
  
spring:
  application: 
    name: status
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LiquidSnake1979/ConfigServerReto
          default-label: main
          search-paths: 
          - '*service'
